# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
