# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
