# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170503_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.CharField(default='http://icons.iconarchive.com/icons/iconsmind/outline/512/CD-icon.png', max_length=100),
        ),
    ]
