# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_music_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(default='Your lyrics here: ', max_length=1000),
        ),
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
